[phases.setup]
nixPkgs = ["php83", "php83Packages.composer", "nodejs_20"]

[phases.build]
cmds = [
    "composer install --no-dev",
    "npm install",
    "npm run build",
    "ls -la public/build" # Untuk memverifikasi di log kalau file build sudah jadi
]

[start]
cmd = "php artisan config:clear && php artisan view:clear && php -S 0.0.0.0:$PORT -t public"